{% set name = "global-chem" %}
{% set version = "1.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/global_chem-{{ version }}.tar.gz
  sha256: 33847fdf727fdb1c351ad3f93c546d0a5e8e9d056d94207acfe335222076bafb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - global_chem
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.github.com/Sulstice/global-chem
  summary: A Chemical Knowledge Graph of What is Common in the World.
  license: MPL-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
