{% set name = "global-chem" %}
{% set version = "1.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/global_chem-{{ version }}.tar.gz
  sha256: 4a81aed3c6e4009591b8d95a81511d8e19ab69ff51bebb6be8548e2ff9d11492

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - global_chem
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.github.com/Sulstice/global-chem
  summary: A Chemical Knowledge Graph of What is Common in the World.
  license: MPL-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
